# Generated by Django 4.1 on 2022-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_city_constraints_package_price_subcategory_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
